<a href="https://colab.research.google.com/github/miinsss/Capstone-Project/blob/main/Random_Forest_and_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libaries

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import recall_score
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from tqdm import tqdm
from sklearn.model_selection import GridSearchCV

# Load the data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

# Load the contract_classification.csv file
contract_class_path = '/content/drive/MyDrive/Colab Notebooks/Capstone_Data/Capstone/Data/contract_classification.csv'
contract_class = pd.read_csv(contract_class_path)



# Display the first few rows to verify content
print(contract_class.head())



Mounted at /content/drive


<ipython-input-2-56a844a11275>:6: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  contract_class = pd.read_csv(contract_class_path)


     ANO_SID CORPORATE_DEVISION   ORTPLZ  ORTS-NAME               STRASSE  \
0  4114028.0                VHV  42109.0  Wuppertal     Hans-Böckler-Str.   
1  4114039.0                VHV  42277.0  Wuppertal       Liegnitzer Str.   
2  4114045.0                VHV  42389.0  Wuppertal             Rascheweg   
3  4114049.0                VGV  42277.0  Wuppertal               Am Diek   
4  4114055.0                VHV  42553.0    Velbert  Emil-Schniewind-Str.   

   SUM_INSURED CONSTRACTION_DESIGN  CONSTRUCTION_YEAR        WFL ZONE  ...  \
0      71081.0      NORMAL_VENTURE        1967.565648   69.00000  2.0  ...   
1      55708.0      NORMAL_VENTURE        1967.565648   65.00000  4.0  ...   
2      74148.0      DESIGN_CLASS_I        1967.565648   75.00000  1.0  ...   
3     664000.0      NORMAL_VENTURE        1967.565648  106.24368  NaN  ...   
4      75682.0      NORMAL_VENTURE        1967.565648  119.00000  2.0  ...   

   DRAIN_PIPE_INSURED  PRODUCTLINE  PRIOR_DAMAGES UVV-KZ  UNDERWRITE

In [3]:
print(contract_class['DAMAGE'].value_counts())


na_counts = contract_class.isna().sum()

print(na_counts)

DAMAGE
0    11389665
1      184774
Name: count, dtype: int64
ANO_SID                     55
CORPORATE_DEVISION           0
ORTPLZ                  102482
ORTS-NAME                 3901
STRASSE                  16338
SUM_INSURED              16503
CONSTRACTION_DESIGN    1188450
CONSTRUCTION_YEAR            0
WFL                      16670
ZONE                    988470
SF-SYSTEM              9717058
TYPE_OF_DEDUCTIBLE           0
DRAIN_PIPE_INSURED           0
PRODUCTLINE            1735746
PRIOR_DAMAGES                0
UVV-KZ                       0
UNDERWRITER                  0
PARTY-ID                   203
contract_year                0
PIPE_PREMIUM_AMOUNT        167
YEAR                         0
DAMAGE                       0
dtype: int64


# Models

## Preprocess the data

In [4]:
#Choose variables where it makes logical sense

initial_features = contract_class.loc[:, ['CORPORATE_DEVISION','ORTPLZ',  'SUM_INSURED', 'CONSTRACTION_DESIGN','CONSTRUCTION_YEAR','WFL','ZONE','DRAIN_PIPE_INSURED','PRODUCTLINE', 'PRIOR_DAMAGES', 'UVV-KZ', 'UNDERWRITER','DAMAGE']]

print(initial_features['DAMAGE'].value_counts())

initial_features_clean = initial_features.dropna()

print(initial_features_clean['DAMAGE'].value_counts())

DAMAGE
0    11389665
1      184774
Name: count, dtype: int64
DAMAGE
0    8516533
1     120574
Name: count, dtype: int64


In [5]:
# Choose columns to encode to binary variables

columns_to_encode = ['CORPORATE_DEVISION','CONSTRACTION_DESIGN', 'PRODUCTLINE', 'UNDERWRITER', 'ZONE']

# Create Binary Variables
features_binary = pd.get_dummies(initial_features_clean, columns=columns_to_encode, drop_first=True)

print(features_binary.head())

    ORTPLZ  SUM_INSURED  CONSTRUCTION_YEAR    WFL  DRAIN_PIPE_INSURED  \
0  42109.0      71081.0        1967.565648   69.0                   0   
1  42277.0      55708.0        1967.565648   65.0                   0   
2  42389.0      74148.0        1967.565648   75.0                   0   
4  42553.0      75682.0        1967.565648  119.0                   0   
5  42113.0      70000.0        1967.565648  100.0                   0   

   PRIOR_DAMAGES  UVV-KZ  DAMAGE  CORPORATE_DEVISION_VHV  \
0              0       1       0                    True   
1              0       1       0                    True   
2              0       1       0                    True   
4              0       1       0                    True   
5              0       1       0                    True   

   CONSTRACTION_DESIGN_CARAVAN_MOTORHOME  ...  ZONE_4  ZONE_4.0  ZONE_5  \
0                                  False  ...   False     False   False   
1                                  False  ...   Fa

## Random Forest

In [ ]:
# Define feature and target

X = features_binary.drop(columns=['DAMAGE'])
y = features_binary['DAMAGE']

# Split into test and training

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize RandomUnderSampler
under_sampler = RandomUnderSampler(random_state=42)

# Resample the training data
X_resampled, y_resampled = under_sampler.fit_resample(X_train, y_train)

In [ ]:
# Initializing Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=50, random_state=42)

# Training the classifier
rf_classifier.fit(X_resampled, y_resampled)

# Making probability predictions
y_pred_proba = rf_classifier.predict_proba(X_test)


In [ ]:
# Evaluating the model

# Converting probabilities to class predictions
y_pred = np.argmax(y_pred_proba, axis=1)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generating confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Displaying confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# Extracting TP, FP, TN, FN from the confusion matrix
TN = conf_matrix[0][0]
FP = conf_matrix[0][1]
FN = conf_matrix[1][0]
TP = conf_matrix[1][1]

# Printing TP, FP, TN, FN
print("True Positives:", TP)
print("False Positives:", FP)
print("True Negatives:", TN)
print("False Negatives:", FN)

# Classification report
print(classification_report(y_test, y_pred))
# With undersampling accuracy gets worse, but we detect more TRUE Positives. Still way more false positive

Accuracy: 0.7853703379950007
Confusion Matrix:
[[1338839  364364]
 [   6392   17827]]
True Positives: 17827
False Positives: 364364
True Negatives: 1338839
False Negatives: 6392
              precision    recall  f1-score   support

           0       1.00      0.79      0.88   1703203
           1       0.05      0.74      0.09     24219

    accuracy                           0.79   1727422
   macro avg       0.52      0.76      0.48   1727422
weighted avg       0.98      0.79      0.87   1727422



In [ ]:
# Feature-importnace analysis
feature_importance = rf_classifier.feature_importances_

# Display results
print("Feature Importance:")
for i, feature in enumerate(X_train.columns):
    print(f"{feature}: {feature_importance[i]}")

Feature Importance:
ORTPLZ: 0.22950934268938258
SUM_INSURED: 0.3436387893280586
CONSTRUCTION_YEAR: 0.10233732052560082
WFL: 0.11902210383701167
DRAIN_PIPE_INSURED: 0.0
PRIOR_DAMAGES: 0.004227427149212484
UVV-KZ: 0.014137294705900449
CORPORATE_DEVISION_VHV: 0.1219592231461422
CONSTRACTION_DESIGN_CARAVAN_MOTORHOME: 8.26432256751105e-06
CONSTRACTION_DESIGN_DESIGN_CLASS_I: 0.00027824805381932284
CONSTRACTION_DESIGN_DESIGN_CLASS_II: 0.0
CONSTRACTION_DESIGN_DESIGN_CLASS_III: 7.249581611118396e-06
CONSTRACTION_DESIGN_DESIGN_CLASS_IV: 1.330879859145523e-06
CONSTRACTION_DESIGN_DESIGN_CLASS_V: 2.0118167934125968e-07
CONSTRACTION_DESIGN_NORMAL_VENTURE: 0.0010789227884194744
CONSTRACTION_DESIGN_PREDOMINANTLY_WOODEN_ROOF: 0.00014440976673366968
CONSTRACTION_DESIGN_PREFAB_HOUSE: 0.0006388190920825517
CONSTRACTION_DESIGN_PREFAB_HOUSE_I: 0.0
PRODUCTLINE_Kompakt: 0.0061697423506620365
PRODUCTLINE_Plus: 0.001953922569924123
PRODUCTLINE_Premium: 0.001659283059399923
PRODUCTLINE_Sonst: 0.01468830110913276

## Random Forest with Rolling window

In [6]:
#Choose variables where it makes logical including year column

initial_features = contract_class.loc[:, ['CORPORATE_DEVISION','ORTPLZ',  'SUM_INSURED', 'CONSTRACTION_DESIGN','CONSTRUCTION_YEAR','WFL','ZONE','DRAIN_PIPE_INSURED','PRODUCTLINE', 'PRIOR_DAMAGES', 'UVV-KZ', 'UNDERWRITER','DAMAGE', 'YEAR']]

initial_features_clean = initial_features.dropna()

In [7]:
# Choose columns to encode to binary variables

columns_to_encode = ['CORPORATE_DEVISION','CONSTRACTION_DESIGN', 'PRODUCTLINE', 'UNDERWRITER', 'ZONE']

# Create Binary Variables
features_binary = pd.get_dummies(initial_features_clean, columns=columns_to_encode, drop_first=True)


In [8]:
# Define feature and target

X = features_binary.drop(columns=['DAMAGE'])
y = features_binary['DAMAGE']

YEAR_INDEX = features_binary.columns.get_loc('YEAR')
print(YEAR_INDEX)

8


In [ ]:
# Create a list of unique years in the data
years = sorted(features_binary['YEAR'].unique())
# Initialize lists to store results
recall_scores = []

# Loop over each year for rolling window estimation
for i in tqdm(range(len(years) - 1)):
    train_year = years[i]
    test_year = years[i + 1]

    # Split data into training and testing sets based on year
    X_train = X[features_binary['YEAR'] == train_year]
    y_train = y[features_binary['YEAR'] == train_year]
    X_test = X[features_binary['YEAR'] == test_year]
    y_test = y[features_binary['YEAR'] == test_year]

    # Initialize and train Random Forest classifier
    rf_classifier = RandomForestClassifier(n_estimators=50, random_state=42)
    rf_classifier.fit(X_train, y_train)

    # Make predictions (probabilities)
    y_prob = rf_classifier.predict_proba(X_test)[:, 1]

    # Convert probabilities to binary predictions based on a threshold (e.g., 0.5)
    y_pred = (y_prob >= 0.5).astype(int)

    # Calculate accuracy for the current year
    accuracy = accuracy_score(y_test, y_pred)

    # Calculate recall score
    recall = recall_score(y_test, y_pred)
    recall_scores.append((test_year, recall))

    # Print the classification report for each year
    print(f"Classification report for year {test_year}:")
    print(classification_report(y_test, y_pred))

    # Generating confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for year {test_year}:")
    print(conf_matrix)

    # Extracting TP, FP, TN, FN from the confusion matrix
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    TP = conf_matrix[1][1]

    # Printing TP, FP, TN, FN
    print("True Positives:", TP)
    print("False Positives:", FP)
    print("True Negatives:", TN)
    print("False Negatives:", FN)
# Print recall scores
for year, score in recall_scores:
    print(f"Year: {year}, Recall Score: {score}")



  0%|          | 0/10 [00:00<?, ?it/s]

Classification report for year 2015:


 10%|█         | 1/10 [01:08<10:20, 68.93s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    775271
           1       0.46      0.28      0.35      9736

    accuracy                           0.99    785007
   macro avg       0.73      0.64      0.67    785007
weighted avg       0.98      0.99      0.99    785007

Confusion Matrix for year 2015:
[[772052   3219]
 [  6993   2743]]
True Positives: 2743
False Positives: 3219
True Negatives: 772052
False Negatives: 6993
Classification report for year 2016:


 20%|██        | 2/10 [02:21<09:30, 71.29s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    806222
           1       0.46      0.24      0.32     10815

    accuracy                           0.99    817037
   macro avg       0.73      0.62      0.65    817037
weighted avg       0.98      0.99      0.98    817037

Confusion Matrix for year 2016:
[[803211   3011]
 [  8219   2596]]
True Positives: 2596
False Positives: 3011
True Negatives: 803211
False Negatives: 8219
Classification report for year 2017:


 30%|███       | 3/10 [03:35<08:27, 72.47s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    761669
           1       0.48      0.23      0.31     10459

    accuracy                           0.99    772128
   macro avg       0.74      0.61      0.65    772128
weighted avg       0.98      0.99      0.98    772128

Confusion Matrix for year 2017:
[[759057   2612]
 [  8032   2427]]
True Positives: 2427
False Positives: 2612
True Negatives: 759057
False Negatives: 8032
Classification report for year 2018:


 40%|████      | 4/10 [04:44<07:05, 70.90s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    764349
           1       0.39      0.15      0.22     11440

    accuracy                           0.98    775789
   macro avg       0.69      0.58      0.61    775789
weighted avg       0.98      0.98      0.98    775789

Confusion Matrix for year 2018:
[[761545   2804]
 [  9682   1758]]
True Positives: 1758
False Positives: 2804
True Negatives: 761545
False Negatives: 9682
Classification report for year 2019:


 50%|█████     | 5/10 [05:58<05:59, 71.96s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    771495
           1       0.39      0.17      0.23     12480

    accuracy                           0.98    783975
   macro avg       0.69      0.58      0.61    783975
weighted avg       0.98      0.98      0.98    783975

Confusion Matrix for year 2019:
[[768278   3217]
 [ 10412   2068]]
True Positives: 2068
False Positives: 3217
True Negatives: 768278
False Negatives: 10412
Classification report for year 2020:


 60%|██████    | 6/10 [07:17<04:57, 74.42s/it]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    780559
           1       0.39      0.16      0.23     14376

    accuracy                           0.98    794935
   macro avg       0.69      0.58      0.61    794935
weighted avg       0.97      0.98      0.98    794935

Confusion Matrix for year 2020:
[[776952   3607]
 [ 12049   2327]]
True Positives: 2327
False Positives: 3607
True Negatives: 776952
False Negatives: 12049
Classification report for year 2021:


 70%|███████   | 7/10 [08:40<03:51, 77.33s/it]

              precision    recall  f1-score   support

           0       0.98      0.99      0.99    788098
           1       0.37      0.15      0.21     15770

    accuracy                           0.98    803868
   macro avg       0.68      0.57      0.60    803868
weighted avg       0.97      0.98      0.97    803868

Confusion Matrix for year 2021:
[[784070   4028]
 [ 13386   2384]]
True Positives: 2384
False Positives: 4028
True Negatives: 784070
False Negatives: 13386
Classification report for year 2022:


 80%|████████  | 8/10 [10:02<02:37, 78.63s/it]

              precision    recall  f1-score   support

           0       0.99      0.99      0.99    797092
           1       0.30      0.14      0.19     13298

    accuracy                           0.98    810390
   macro avg       0.64      0.57      0.59    810390
weighted avg       0.97      0.98      0.98    810390

Confusion Matrix for year 2022:
[[792603   4489]
 [ 11415   1883]]
True Positives: 1883
False Positives: 4489
True Negatives: 792603
False Negatives: 11415
Classification report for year 2023:


 90%|█████████ | 9/10 [11:25<01:20, 80.13s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    800711
           1       0.26      0.11      0.15     11149

    accuracy                           0.98    811860
   macro avg       0.62      0.55      0.57    811860
weighted avg       0.98      0.98      0.98    811860

Confusion Matrix for year 2023:
[[797130   3581]
 [  9921   1228]]
True Positives: 1228
False Positives: 3581
True Negatives: 797130
False Negatives: 9921
Classification report for year 2024:


100%|██████████| 10/10 [12:46<00:00, 76.70s/it]

              precision    recall  f1-score   support

           0       1.00      0.99      1.00    806672
           1       0.04      0.10      0.06      2049

    accuracy                           0.99    808721
   macro avg       0.52      0.55      0.53    808721
weighted avg       1.00      0.99      0.99    808721

Confusion Matrix for year 2024:
[[801513   5159]
 [  1841    208]]
True Positives: 208
False Positives: 5159
True Negatives: 801513
False Negatives: 1841
Year: 2015, Recall Score: 0.2817378800328677
Year: 2016, Recall Score: 0.24003698566805362
Year: 2017, Recall Score: 0.23204895305478535
Year: 2018, Recall Score: 0.15367132867132868
Year: 2019, Recall Score: 0.1657051282051282
Year: 2020, Recall Score: 0.16186700055648304
Year: 2021, Recall Score: 0.1511731135066582
Year: 2022, Recall Score: 0.1416002406376899
Year: 2023, Recall Score: 0.11014440757018566
Year: 2024, Recall Score: 0.10151293313811616


## Random Forrest with expanding window

In [9]:

# Define the parameter grid for Grid Search
param_grid = {
    'n_estimators': [10, 20],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
}

# Create a list of unique years in the data
years = sorted(features_binary['YEAR'].unique())
# Initialize lists to store results
recall_scores = []

# Loop over each year for rolling window estimation
for i in tqdm(range(1, len(years))):
    test_year = years[i]
    train_years = years[:i]  # All years up to the year before test_year

    # Split data into training and testing sets based on year
    X_train = X[features_binary['YEAR'].isin(train_years)]
    y_train = y[features_binary['YEAR'].isin(train_years)]
    X_test = X[features_binary['YEAR'] == test_year]
    y_test = y[features_binary['YEAR'] == test_year]

    # Initialize the Random Forest classifier
    rf_classifier = RandomForestClassifier(random_state=42)

    # Perform Grid Search with cross-validation
    grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid,
                               cv=3, n_jobs=-1, verbose=2, scoring='recall')
    grid_search.fit(X_train, y_train)

    # Get the best model from Grid Search
    best_rf_classifier = grid_search.best_estimator_

    # Make predictions (probabilities)
    y_prob = best_rf_classifier.predict_proba(X_test)[:, 1]

    # Convert probabilities to binary predictions based on a threshold (e.g., 0.5)
    y_pred = (y_prob >= 0.5).astype(int)

    # Calculate accuracy for the current year
    accuracy = accuracy_score(y_test, y_pred)

    # Calculate recall score
    recall = recall_score(y_test, y_pred)
    recall_scores.append((test_year, recall))

    # Print the best parameters for the current year
    print(f"Best parameters for year {test_year}: {grid_search.best_params_}")

    # Print the classification report for each year
    print(f"Classification report for year {test_year}:")
    print(classification_report(y_test, y_pred))

    # Generating confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for year {test_year}:")
    print(conf_matrix)

    # Extracting TP, FP, TN, FN from the confusion matrix
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    TP = conf_matrix[1][1]

    # Printing TP, FP, TN, FN
    print("True Positives:", TP)
    print("False Positives:", FP)
    print("True Negatives:", TN)
    print("False Negatives:", FN)

# Print recall scores
for year, score in recall_scores:
    print(f"Year: {year}, Recall Score: {score}")

  0%|          | 0/10 [00:00<?, ?it/s]

Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2015: {'max_depth': 20, 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 10}
Classification report for year 2015:


 10%|█         | 1/10 [07:04<1:03:38, 424.32s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      1.00    768070
           1       0.91      0.22      0.35      9606

    accuracy                           0.99    777676
   macro avg       0.95      0.61      0.67    777676
weighted avg       0.99      0.99      0.99    777676

Confusion Matrix for year 2015:
[[767850    220]
 [  7489   2117]]
True Positives: 2117
False Positives: 220
True Negatives: 767850
False Negatives: 7489
Fitting 3 folds for each of 54 candidates, totalling 162 fits


/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best parameters for year 2016: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 10}
Classification report for year 2016:


 20%|██        | 2/10 [24:44<1:46:28, 798.53s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    797816
           1       0.85      0.21      0.33     10694

    accuracy                           0.99    808510
   macro avg       0.92      0.60      0.66    808510
weighted avg       0.99      0.99      0.99    808510

Confusion Matrix for year 2016:
[[797431    385]
 [  8475   2219]]
True Positives: 2219
False Positives: 385
True Negatives: 797431
False Negatives: 8475
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2017: {'max_depth': 30, 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 10}
Classification report for year 2017:


 30%|███       | 3/10 [51:08<2:14:58, 1156.98s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    754974
           1       0.93      0.19      0.32     10393

    accuracy                           0.99    765367
   macro avg       0.96      0.60      0.66    765367
weighted avg       0.99      0.99      0.99    765367

Confusion Matrix for year 2017:
[[754826    148]
 [  8403   1990]]
True Positives: 1990
False Positives: 148
True Negatives: 754826
False Negatives: 8403
Fitting 3 folds for each of 54 candidates, totalling 162 fits


/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best parameters for year 2018: {'max_depth': 30, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 10}
Classification report for year 2018:


 40%|████      | 4/10 [1:26:39<2:34:08, 1541.39s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    756661
           1       0.82      0.13      0.23     11321

    accuracy                           0.99    767982
   macro avg       0.90      0.57      0.61    767982
weighted avg       0.98      0.99      0.98    767982

Confusion Matrix for year 2018:
[[756337    324]
 [  9841   1480]]
True Positives: 1480
False Positives: 324
True Negatives: 756337
False Negatives: 9841
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2019: {'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 10}
Classification report for year 2019:


 50%|█████     | 5/10 [2:14:33<2:48:30, 2022.10s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    762788
           1       0.63      0.15      0.25     12360

    accuracy                           0.99    775148
   macro avg       0.81      0.58      0.62    775148
weighted avg       0.98      0.99      0.98    775148

Confusion Matrix for year 2019:
[[761691   1097]
 [ 10458   1902]]
True Positives: 1902
False Positives: 1097
True Negatives: 761691
False Negatives: 10458
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2020: {'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 10}
Classification report for year 2020:


 60%|██████    | 6/10 [3:18:39<2:56:08, 2642.20s/it]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    773937
           1       0.76      0.14      0.24     14300

    accuracy                           0.98    788237
   macro avg       0.87      0.57      0.62    788237
weighted avg       0.98      0.98      0.98    788237

Confusion Matrix for year 2020:
[[773275    662]
 [ 12241   2059]]
True Positives: 2059
False Positives: 662
True Negatives: 773275
False Negatives: 12241
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2021: {'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 10}
Classification report for year 2021:


 70%|███████   | 7/10 [4:38:11<2:46:55, 3338.50s/it]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    780481
           1       0.77      0.12      0.21     15702

    accuracy                           0.98    796183
   macro avg       0.88      0.56      0.60    796183
weighted avg       0.98      0.98      0.98    796183

Confusion Matrix for year 2021:
[[779909    572]
 [ 13754   1948]]
True Positives: 1948
False Positives: 572
True Negatives: 779909
False Negatives: 13754
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2022: {'max_depth': 30, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 10}
Classification report for year 2022:


 80%|████████  | 8/10 [6:13:12<2:16:21, 4090.75s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    791578
           1       0.71      0.12      0.21     13219

    accuracy                           0.98    804797
   macro avg       0.85      0.56      0.60    804797
weighted avg       0.98      0.98      0.98    804797

Confusion Matrix for year 2022:
[[790914    664]
 [ 11596   1623]]
True Positives: 1623
False Positives: 664
True Negatives: 790914
False Negatives: 11596
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters for year 2023: {'max_depth': 30, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 20}
Classification report for year 2023:


 90%|█████████ | 9/10 [8:06:04<1:22:08, 4928.69s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    794432
           1       0.72      0.10      0.17     11113

    accuracy                           0.99    805545
   macro avg       0.85      0.55      0.58    805545
weighted avg       0.98      0.99      0.98    805545

Confusion Matrix for year 2023:
[[794003    429]
 [ 10016   1097]]
True Positives: 1097
False Positives: 429
True Negatives: 794003
False Negatives: 10016
Fitting 3 folds for each of 54 candidates, totalling 162 fits


/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best parameters for year 2024: {'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 10}
Classification report for year 2024:


100%|██████████| 10/10 [10:06:31<00:00, 3639.15s/it]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    799514
           1       0.14      0.09      0.11      2048

    accuracy                           1.00    801562
   macro avg       0.57      0.54      0.55    801562
weighted avg       1.00      1.00      1.00    801562

Confusion Matrix for year 2024:
[[798377   1137]
 [  1868    180]]
True Positives: 180
False Positives: 1137
True Negatives: 798377
False Negatives: 1868
Year: 2015, Recall Score: 0.22038309389964605
Year: 2016, Recall Score: 0.20749953244810174
Year: 2017, Recall Score: 0.1914750312710478
Year: 2018, Recall Score: 0.13073050083914847
Year: 2019, Recall Score: 0.15388349514563107
Year: 2020, Recall Score: 0.143986013986014
Year: 2021, Recall Score: 0.12406062921920774
Year: 2022, Recall Score: 0.12277781980482638
Year: 2023, Recall Score: 0.09871321875281203
Year: 2024, Recall Score: 0.087890625


In [12]:
probabilities_last_year = y_prob

# Convert the probabilities to a DataFrame
probabilities_df = pd.DataFrame(probabilities_last_year, columns=['Probability'])

# Save to a CSV file
probabilities_df.to_csv('probabilities_last_year.csv', index=False)

# Count the number of probabilities greater than 1
count_greater_than_one = (probabilities_last_year > 1).sum()

# Print the count
print(f"Number of entries in the probability array greater than 1: {count_greater_than_one}")

Number of entries in the probability array greater than 1: 0


# Naive Bayes

In [14]:
# Define initial features
initial_features = contract_class.loc[:, ['CORPORATE_DEVISION', 'SUM_INSURED', 'CONSTRACTION_DESIGN', 'CONSTRUCTION_YEAR', 'WFL', 'ZONE', 'DRAIN_PIPE_INSURED', 'PRODUCTLINE', 'PRIOR_DAMAGES', 'UVV-KZ', 'UNDERWRITER', 'DAMAGE', 'YEAR']]
initial_features_clean = initial_features.dropna()

# Define feature and target
columns_to_encode = ['CORPORATE_DEVISION', 'CONSTRACTION_DESIGN', 'PRODUCTLINE', 'UNDERWRITER', 'ZONE']

# Create binary variables using one-hot encoding
features_binary = pd.get_dummies(initial_features_clean, columns=columns_to_encode, drop_first=True)

X = features_binary.drop(columns=['DAMAGE'])
y = features_binary['DAMAGE']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Separate continuous and discrete features
continuous_features = ['SUM_INSURED', 'CONSTRUCTION_YEAR']
# The discrete features need to be adjusted after one-hot encoding
discrete_features = list(set(X.columns) - set(continuous_features))

In [ ]:
# Create a list of unique years in the data
years = sorted(features_binary['YEAR'].unique())
# Initialize lists to store results
recall_scores = []

# Loop over each year for rolling window estimation
for i in tqdm(range(len(years) - 1)):
    train_year = years[i]
    test_year = years[i + 1]

    # Split data into training and testing sets based on year
    X_train = X[features_binary['YEAR'] == train_year]
    y_train = y[features_binary['YEAR'] == train_year]
    X_test = X[features_binary['YEAR'] == test_year]
    y_test = y[features_binary['YEAR'] == test_year]

# Train GaussianNB on continuous features
    gnb = GaussianNB()
    gnb.fit(X_train[continuous_features], y_train)

# Train MultinomialNB on discrete features
    mnb = MultinomialNB()
    mnb.fit(X_train[discrete_features], y_train)

    # Get predicted probabilities for continuous and discrete features
    gnb_prob = gnb.predict_proba(X_test[continuous_features])[:, 1]
    mnb_prob = mnb.predict_proba(X_test[discrete_features])[:, 1]

    # Combine probabilities (you can average them, use weighted sum, etc.)
    combined_prob = (gnb_prob + mnb_prob) / 2

    # Convert probabilities to binary predictions based on a threshold (e.g., 0.5)
    y_pred = (combined_prob >= 0.5).astype(int)

    # Calculate accuracy for the current year
    accuracy = accuracy_score(y_test, y_pred)

    # Calculate recall score
    recall = recall_score(y_test, y_pred)
    recall_scores.append((test_year, recall))

    # Print the classification report for each year
    print(f"Classification report for year {test_year}:")
    print(classification_report(y_test, y_pred))

    # Generating confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for year {test_year}:")
    print(conf_matrix)

    # Extracting TP, FP, TN, FN from the confusion matrix
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    TP = conf_matrix[1][1]

    # Printing TP, FP, TN, FN
    print("True Positives:", TP)
    print("False Positives:", FP)
    print("True Negatives:", TN)
    print("False Negatives:", FN)
# Print recall scores
for year, score in recall_scores:
    print(f"Year: {year}, Recall Score: {score}")

  0%|          | 0/10 [00:00<?, ?it/s]

Classification report for year 2015:


 10%|█         | 1/10 [00:03<00:27,  3.02s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    775271
           1       0.42      0.12      0.19      9736

    accuracy                           0.99    785007
   macro avg       0.70      0.56      0.59    785007
weighted avg       0.98      0.99      0.98    785007

Confusion Matrix for year 2015:
[[773616   1655]
 [  8536   1200]]
True Positives: 1200
False Positives: 1655
True Negatives: 773616
False Negatives: 8536
Classification report for year 2016:


 20%|██        | 2/10 [00:06<00:26,  3.28s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    806222
           1       0.48      0.11      0.18     10815

    accuracy                           0.99    817037
   macro avg       0.74      0.55      0.59    817037
weighted avg       0.98      0.99      0.98    817037

Confusion Matrix for year 2016:
[[804964   1258]
 [  9640   1175]]
True Positives: 1175
False Positives: 1258
True Negatives: 804964
False Negatives: 9640
Classification report for year 2017:


 30%|███       | 3/10 [00:09<00:22,  3.15s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    761669
           1       0.42      0.10      0.16     10459

    accuracy                           0.99    772128
   macro avg       0.70      0.55      0.57    772128
weighted avg       0.98      0.99      0.98    772128

Confusion Matrix for year 2017:
[[760286   1383]
 [  9455   1004]]
True Positives: 1004
False Positives: 1383
True Negatives: 760286
False Negatives: 9455
Classification report for year 2018:


 40%|████      | 4/10 [00:12<00:18,  3.08s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    764349
           1       0.16      0.03      0.05     11440

    accuracy                           0.98    775789
   macro avg       0.57      0.51      0.52    775789
weighted avg       0.97      0.98      0.98    775789

Confusion Matrix for year 2018:
[[762597   1752]
 [ 11106    334]]
True Positives: 334
False Positives: 1752
True Negatives: 762597
False Negatives: 11106
Classification report for year 2019:


 50%|█████     | 5/10 [00:15<00:15,  3.04s/it]

              precision    recall  f1-score   support

           0       0.98      0.99      0.99    771495
           1       0.09      0.03      0.04     12480

    accuracy                           0.98    783975
   macro avg       0.54      0.51      0.52    783975
weighted avg       0.97      0.98      0.97    783975

Confusion Matrix for year 2019:
[[767538   3957]
 [ 12103    377]]
True Positives: 377
False Positives: 3957
True Negatives: 767538
False Negatives: 12103
Classification report for year 2020:


 60%|██████    | 6/10 [00:18<00:12,  3.02s/it]

              precision    recall  f1-score   support

           0       0.98      0.99      0.99    780559
           1       0.08      0.03      0.05     14376

    accuracy                           0.98    794935
   macro avg       0.53      0.51      0.52    794935
weighted avg       0.97      0.98      0.97    794935

Confusion Matrix for year 2020:
[[775127   5432]
 [ 13900    476]]
True Positives: 476
False Positives: 5432
True Negatives: 775127
False Negatives: 13900
Classification report for year 2021:


 70%|███████   | 7/10 [00:21<00:09,  3.02s/it]

              precision    recall  f1-score   support

           0       0.98      0.99      0.98    788098
           1       0.05      0.04      0.04     15770

    accuracy                           0.97    803868
   macro avg       0.52      0.51      0.51    803868
weighted avg       0.96      0.97      0.97    803868

Confusion Matrix for year 2021:
[[777761  10337]
 [ 15188    582]]
True Positives: 582
False Positives: 10337
True Negatives: 777761
False Negatives: 15188
Classification report for year 2022:


 80%|████████  | 8/10 [00:24<00:06,  3.05s/it]

              precision    recall  f1-score   support

           0       0.98      0.98      0.98    797092
           1       0.04      0.05      0.05     13298

    accuracy                           0.96    810390
   macro avg       0.51      0.52      0.51    810390
weighted avg       0.97      0.96      0.97    810390

Confusion Matrix for year 2022:
[[780519  16573]
 [ 12590    708]]
True Positives: 708
False Positives: 16573
True Negatives: 780519
False Negatives: 12590
Classification report for year 2023:


 90%|█████████ | 9/10 [00:27<00:03,  3.11s/it]

              precision    recall  f1-score   support

           0       0.99      0.97      0.98    800711
           1       0.04      0.07      0.05     11149

    accuracy                           0.96    811860
   macro avg       0.51      0.52      0.51    811860
weighted avg       0.97      0.96      0.97    811860

Confusion Matrix for year 2023:
[[779298  21413]
 [ 10356    793]]
True Positives: 793
False Positives: 21413
True Negatives: 779298
False Negatives: 10356
Classification report for year 2024:


100%|██████████| 10/10 [00:30<00:00,  3.08s/it]

              precision    recall  f1-score   support

           0       1.00      0.96      0.98    806672
           1       0.01      0.08      0.01      2049

    accuracy                           0.96    808721
   macro avg       0.50      0.52      0.49    808721
weighted avg       1.00      0.96      0.98    808721

Confusion Matrix for year 2024:
[[775821  30851]
 [  1877    172]]
True Positives: 172
False Positives: 30851
True Negatives: 775821
False Negatives: 1877
Year: 2015, Recall Score: 0.12325390304026294
Year: 2016, Recall Score: 0.10864539990753583
Year: 2017, Recall Score: 0.09599388086815183
Year: 2018, Recall Score: 0.029195804195804195
Year: 2019, Recall Score: 0.030208333333333334
Year: 2020, Recall Score: 0.03311074012242626
Year: 2021, Recall Score: 0.03690551680405834
Year: 2022, Recall Score: 0.0532410888855467
Year: 2023, Recall Score: 0.07112745537716388
Year: 2024, Recall Score: 0.08394338701805759


In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", report)

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Extracting TP, FP, TN, FN from the confusion matrix
TN = conf_matrix[0][0]
FP = conf_matrix[0][1]
FN = conf_matrix[1][0]
TP = conf_matrix[1][1]

# Printing TP, FP, TN, FN
print("True Positives:", TP)
print("False Positives:", FP)
print("True Negatives:", TN)
print("False Negatives:", FN)

Accuracy: 0.99

Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99   1719308
           1       0.98      0.04      0.08     24428

    accuracy                           0.99   1743736
   macro avg       0.98      0.52      0.54   1743736
weighted avg       0.99      0.99      0.98   1743736


Confusion Matrix:
 [[1719284      24]
 [  23369    1059]]
True Positives: 1059
False Positives: 24
True Negatives: 1719284
False Negatives: 23369


## Naive Bayes with expanding window

In [15]:
# Define parameter grids for GaussianNB and MultinomialNB
gnb_param_grid = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6]
}

mnb_param_grid = {
    'alpha': [0.1, 0.5, 1.0, 2.0]
}

# Create a list of unique years in the data
years = sorted(features_binary['YEAR'].unique())
# Initialize lists to store results
recall_scores = []

# Loop over each year for rolling window estimation
for i in tqdm(range(1, len(years))):
    test_year = years[i]
    train_years = years[:i]  # All years up to the year before test_year

    # Split data into training and testing sets based on year
    X_train = X[features_binary['YEAR'].isin(train_years)]
    y_train = y[features_binary['YEAR'].isin(train_years)]
    X_test = X[features_binary['YEAR'] == test_year]
    y_test = y[features_binary['YEAR'] == test_year]

    # Initialize GaussianNB and perform Grid Search
    gnb = GaussianNB()
    gnb_grid_search = GridSearchCV(estimator=gnb, param_grid=gnb_param_grid, cv=3, n_jobs=-1, scoring='recall')
    gnb_grid_search.fit(X_train[continuous_features], y_train)
    best_gnb = gnb_grid_search.best_estimator_

    # Initialize MultinomialNB and perform Grid Search
    mnb = MultinomialNB()
    mnb_grid_search = GridSearchCV(estimator=mnb, param_grid=mnb_param_grid, cv=3, n_jobs=-1, scoring='recall')
    mnb_grid_search.fit(X_train[discrete_features], y_train)
    best_mnb = mnb_grid_search.best_estimator_

    # Get predicted probabilities for continuous and discrete features
    gnb_prob = best_gnb.predict_proba(X_test[continuous_features])[:, 1]
    mnb_prob = best_mnb.predict_proba(X_test[discrete_features])[:, 1]

    # Combine probabilities (you can average them, use weighted sum, etc.)
    combined_prob = (gnb_prob + mnb_prob) / 2

    # Convert probabilities to binary predictions based on a threshold (e.g., 0.5)
    y_pred = (combined_prob >= 0.5).astype(int)

    # Calculate accuracy for the current year
    accuracy = accuracy_score(y_test, y_pred)

    # Calculate recall score
    recall = recall_score(y_test, y_pred)
    recall_scores.append((test_year, recall))

    # Print the best parameters for the current year
    print(f"Best parameters for GaussianNB in year {test_year}: {gnb_grid_search.best_params_}")
    print(f"Best parameters for MultinomialNB in year {test_year}: {mnb_grid_search.best_params_}")

    # Print the classification report for each year
    print(f"Classification report for year {test_year}:")
    print(classification_report(y_test, y_pred))

    # Generating confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for year {test_year}:")
    print(conf_matrix)

    # Extracting TP, FP, TN, FN from the confusion matrix
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    TP = conf_matrix[1][1]

    # Printing TP, FP, TN, FN
    print("True Positives:", TP)
    print("False Positives:", FP)
    print("True Negatives:", TN)
    print("False Negatives:", FN)

# Print recall scores
for year, score in recall_scores:
    print(f"Year: {year}, Recall Score: {score}")

  0%|          | 0/10 [00:00<?, ?it/s]

Best parameters for GaussianNB in year 2015: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2015: {'alpha': 0.1}
Classification report for year 2015:


 10%|█         | 1/10 [00:08<01:17,  8.58s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    775271
           1       0.42      0.12      0.19      9736

    accuracy                           0.99    785007
   macro avg       0.70      0.56      0.59    785007
weighted avg       0.98      0.99      0.98    785007

Confusion Matrix for year 2015:
[[773620   1651]
 [  8539   1197]]
True Positives: 1197
False Positives: 1651
True Negatives: 773620
False Negatives: 8539
Best parameters for GaussianNB in year 2016: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2016: {'alpha': 2.0}
Classification report for year 2016:


 20%|██        | 2/10 [00:18<01:15,  9.39s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    806222
           1       0.43      0.11      0.17     10815

    accuracy                           0.99    817037
   macro avg       0.71      0.55      0.58    817037
weighted avg       0.98      0.99      0.98    817037

Confusion Matrix for year 2016:
[[804652   1570]
 [  9634   1181]]
True Positives: 1181
False Positives: 1570
True Negatives: 804652
False Negatives: 9634
Best parameters for GaussianNB in year 2017: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2017: {'alpha': 2.0}
Classification report for year 2017:


 30%|███       | 3/10 [00:31<01:17, 11.00s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    761669
           1       0.40      0.10      0.16     10459

    accuracy                           0.99    772128
   macro avg       0.70      0.55      0.57    772128
weighted avg       0.98      0.99      0.98    772128

Confusion Matrix for year 2017:
[[760187   1482]
 [  9453   1006]]
True Positives: 1006
False Positives: 1482
True Negatives: 760187
False Negatives: 9453
Best parameters for GaussianNB in year 2018: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2018: {'alpha': 0.1}
Classification report for year 2018:


 40%|████      | 4/10 [00:48<01:20, 13.41s/it]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    764349
           1       0.15      0.03      0.05     11440

    accuracy                           0.98    775789
   macro avg       0.57      0.51      0.52    775789
weighted avg       0.97      0.98      0.98    775789

Confusion Matrix for year 2018:
[[762467   1882]
 [ 11105    335]]
True Positives: 335
False Positives: 1882
True Negatives: 762467
False Negatives: 11105
Best parameters for GaussianNB in year 2019: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2019: {'alpha': 0.1}
Classification report for year 2019:


 50%|█████     | 5/10 [01:08<01:19, 15.84s/it]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    771495
           1       0.12      0.03      0.04     12480

    accuracy                           0.98    783975
   macro avg       0.55      0.51      0.52    783975
weighted avg       0.97      0.98      0.98    783975

Confusion Matrix for year 2019:
[[769127   2368]
 [ 12146    334]]
True Positives: 334
False Positives: 2368
True Negatives: 769127
False Negatives: 12146
Best parameters for GaussianNB in year 2020: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2020: {'alpha': 0.1}
Classification report for year 2020:


 60%|██████    | 6/10 [01:32<01:13, 18.38s/it]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    780559
           1       0.11      0.03      0.04     14376

    accuracy                           0.98    794935
   macro avg       0.54      0.51      0.52    794935
weighted avg       0.97      0.98      0.97    794935

Confusion Matrix for year 2020:
[[777226   3333]
 [ 13976    400]]
True Positives: 400
False Positives: 3333
True Negatives: 777226
False Negatives: 13976
Best parameters for GaussianNB in year 2021: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2021: {'alpha': 0.5}
Classification report for year 2021:


 70%|███████   | 7/10 [01:59<01:03, 21.31s/it]

              precision    recall  f1-score   support

           0       0.98      0.99      0.99    788098
           1       0.07      0.03      0.04     15770

    accuracy                           0.97    803868
   macro avg       0.53      0.51      0.51    803868
weighted avg       0.96      0.97      0.97    803868

Confusion Matrix for year 2021:
[[782902   5196]
 [ 15360    410]]
True Positives: 410
False Positives: 5196
True Negatives: 782902
False Negatives: 15360
Best parameters for GaussianNB in year 2022: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2022: {'alpha': 0.1}
Classification report for year 2022:


 80%|████████  | 8/10 [02:30<00:49, 24.57s/it]

              precision    recall  f1-score   support

           0       0.98      0.99      0.99    797092
           1       0.06      0.04      0.05     13298

    accuracy                           0.97    810390
   macro avg       0.52      0.51      0.52    810390
weighted avg       0.97      0.97      0.97    810390

Confusion Matrix for year 2022:
[[789534   7558]
 [ 12814    484]]
True Positives: 484
False Positives: 7558
True Negatives: 789534
False Negatives: 12814
Best parameters for GaussianNB in year 2023: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2023: {'alpha': 0.1}
Classification report for year 2023:


 90%|█████████ | 9/10 [03:07<00:28, 28.48s/it]

              precision    recall  f1-score   support

           0       0.99      0.99      0.99    800711
           1       0.05      0.05      0.05     11149

    accuracy                           0.97    811860
   macro avg       0.52      0.52      0.52    811860
weighted avg       0.97      0.97      0.97    811860

Confusion Matrix for year 2023:
[[790632  10079]
 [ 10566    583]]
True Positives: 583
False Positives: 10079
True Negatives: 790632
False Negatives: 10566
Best parameters for GaussianNB in year 2024: {'var_smoothing': 1e-09}
Best parameters for MultinomialNB in year 2024: {'alpha': 0.1}
Classification report for year 2024:


100%|██████████| 10/10 [03:48<00:00, 22.86s/it]

              precision    recall  f1-score   support

           0       1.00      0.98      0.99    806672
           1       0.01      0.05      0.01      2049

    accuracy                           0.98    808721
   macro avg       0.50      0.52      0.50    808721
weighted avg       1.00      0.98      0.99    808721

Confusion Matrix for year 2024:
[[793852  12820]
 [  1944    105]]
True Positives: 105
False Positives: 12820
True Negatives: 793852
False Negatives: 1944
Year: 2015, Recall Score: 0.12294576828266228
Year: 2016, Recall Score: 0.10920018492834027
Year: 2017, Recall Score: 0.09618510373840711
Year: 2018, Recall Score: 0.029283216783216784
Year: 2019, Recall Score: 0.02676282051282051
Year: 2020, Recall Score: 0.027824151363383415
Year: 2021, Recall Score: 0.02599873176918199
Year: 2022, Recall Score: 0.036396450594074294
Year: 2023, Recall Score: 0.052291685352946454
Year: 2024, Recall Score: 0.05124450951683748
